name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release --nologo      
    - name: Upload artifacts (Core)
      uses: actions/upload-artifact@v2
      with:
        name: February
        path: D:\a\February\February.Core\bin\Release\net6.0-windows\
    - name: Upload artifacts (Dev)
      uses: actions/upload-artifact@v2
      with:
        name: February
        path: D:\a\February\February.Dev\bin\Release\net6.0-windows\
